name: sheva_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Untuk menyimpan data login (nama & gender) secara lokal
  shared_preferences: ^2.5.0
  url_launcher: ^6.3.1   # Tambahkan ini untuk membuka Google Maps
  share_plus: ^10.1.4  # <-- Tambahkan ini untuk fitur berbagi
  image_picker: ^1.1.2  # <-- Tambahkan ini untuk memilih foto

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true