name: sheva_app
description: "SHEVA - Solidarity Hub for Equality, Voice, and Action"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Storage
  shared_preferences: ^2.5.0
  
  # URL & Sharing
  url_launcher: ^6.3.0
  share_plus: ^10.1.4
  
  # Camera & Gallery
  image_picker: ^1.1.2
  
  # Location
  geolocator: ^13.0.0
  geocoding: ^2.1.0
  
  # State Management
  provider: ^6.1.0

  # File storage for profile picture
  path_provider: ^2.1.0
  path: ^1.9.0

  # Untuk ikon custom dari Figma (SVG)
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # TEMPAT UNTUK MENARUH FILE SVG DARI FIGMA
  # assets:
  #   - assets/icons/
  #   - assets/images/